name: CI

# Runs on pushes to master and all pull requests
on:    # yamllint disable-line rule:truthy
    push:
        branches: [main]
    pull_request:

jobs:
    linters:
        name: Linters
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Lint dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r lint-requirements.txt
            - name: Run linters
              run: |
                  flake8 . --count --show-source --statistics
                  black --check --diff .
                  yamllint .
